#ifndef MQL_AUTO_FORWARDS_INCLUDED_62BF601910194BC0
#define MQL_AUTO_FORWARDS_INCLUDED_62BF601910194BC0
// Auto-generated by MQL Clangd. Do not edit — regenerated by "MQL: Create Configuration".
// Forward declarations for top-level functions in /Users/a1-6/Desktop/桌面/workspace/tradingview_mt5_connector/mt5/EaBridge.mq5


#endif
